
server:
  port: 9529

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka
  instance:
    status-page-url-path: /


spring:
  application:
    name: service-feign


feign:
  hystrix:
    enabled: true

