eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka
server:
  port: 9528
spring:
  application:
    name: service-ribbon

# 断路由监控页面集群配置
turbine:
  # 配置Eureka中的serviceId列表，表明监控哪些服务,多个服务用',"分隔
  appConfig: service-ribbon,service-feign
  aggregator:
    # 指定聚合哪些集群，多个使用”,”分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    clusterConfig: default
  clusterNameExpression: new String("default")

